[package]
name = "heimdall-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = { version = "8.0.0"}
nom_locate = { version = "5.0.0"}
serde = { version = "1.0.219", features = ["derive"]}
serde_json = { version = "1.0.140"}
